// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/category/[id]" | "/compare" | "/compare/[slug]" | "/compare/custom" | "/dashboard" | "/learn" | "/learn/[slug]" | "/login" | "/product/[id]" | "/register" | "/smartphone/[id]" | "/topup"
type AppRouteHandlerRoutes = "/api/me" | "/api/wishlist"
type PageRoutes = never
type LayoutRoutes = "/" | "/smartphone"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/me": {}
  "/api/wishlist": {}
  "/category/[id]": { "id": string; }
  "/compare": {}
  "/compare/[slug]": { "slug": string; }
  "/compare/custom": {}
  "/dashboard": {}
  "/learn": {}
  "/learn/[slug]": { "slug": string; }
  "/login": {}
  "/product/[id]": { "id": string; }
  "/register": {}
  "/smartphone": {}
  "/smartphone/[id]": { "id": string; }
  "/topup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/smartphone": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
